//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkyMapsClient.ArkyMapServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ArkyMapService", ConfigurationName="ArkyMapServiceReference.IMapService", CallbackContract=typeof(ArkyMapsClient.ArkyMapServiceReference.IMapServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IMapService {
        
        [System.ServiceModel.OperationContractAttribute(Action="ArkyMapService/IMapService/Login", ReplyAction="ArkyMapService/IMapService/LoginResponse")]
        ArkyMapsDomainModel.ClientUser Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="ArkyMapService/IMapService/Login", ReplyAction="ArkyMapService/IMapService/LoginResponse")]
        System.Threading.Tasks.Task<ArkyMapsDomainModel.ClientUser> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="ArkyMapService/IMapService/Logout")]
        void Logout(long userId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="ArkyMapService/IMapService/Logout")]
        System.Threading.Tasks.Task LogoutAsync(long userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="ArkyMapService/IMapService/QueryPhoneUserById", ReplyAction="ArkyMapService/IMapService/QueryPhoneUserByIdResponse")]
        ArkyMapsDomainModel.PhoneUser QueryPhoneUserById(long userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="ArkyMapService/IMapService/QueryPhoneUserById", ReplyAction="ArkyMapService/IMapService/QueryPhoneUserByIdResponse")]
        System.Threading.Tasks.Task<ArkyMapsDomainModel.PhoneUser> QueryPhoneUserByIdAsync(long userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="ArkyMapService/IMapService/QueryPhoneUsers", ReplyAction="ArkyMapService/IMapService/QueryPhoneUsersResponse")]
        ArkyMapsDomainModel.PhoneUser[] QueryPhoneUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="ArkyMapService/IMapService/QueryPhoneUsers", ReplyAction="ArkyMapService/IMapService/QueryPhoneUsersResponse")]
        System.Threading.Tasks.Task<ArkyMapsDomainModel.PhoneUser[]> QueryPhoneUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="ArkyMapService/IMapService/CreatePhoneUser", ReplyAction="ArkyMapService/IMapService/CreatePhoneUserResponse")]
        bool CreatePhoneUser(ArkyMapsDomainModel.PhoneUser phoneUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="ArkyMapService/IMapService/CreatePhoneUser", ReplyAction="ArkyMapService/IMapService/CreatePhoneUserResponse")]
        System.Threading.Tasks.Task<bool> CreatePhoneUserAsync(ArkyMapsDomainModel.PhoneUser phoneUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="ArkyMapService/IMapService/ModifyPhoneUser", ReplyAction="ArkyMapService/IMapService/ModifyPhoneUserResponse")]
        bool ModifyPhoneUser(ArkyMapsDomainModel.PhoneUser phoneUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="ArkyMapService/IMapService/ModifyPhoneUser", ReplyAction="ArkyMapService/IMapService/ModifyPhoneUserResponse")]
        System.Threading.Tasks.Task<bool> ModifyPhoneUserAsync(ArkyMapsDomainModel.PhoneUser phoneUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="ArkyMapService/IMapService/DeletePhoneUser", ReplyAction="ArkyMapService/IMapService/DeletePhoneUserResponse")]
        bool DeletePhoneUser(ArkyMapsDomainModel.PhoneUser phoneUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="ArkyMapService/IMapService/DeletePhoneUser", ReplyAction="ArkyMapService/IMapService/DeletePhoneUserResponse")]
        System.Threading.Tasks.Task<bool> DeletePhoneUserAsync(ArkyMapsDomainModel.PhoneUser phoneUser);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMapServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="ArkyMapService/IMapService/NewPosition")]
        void NewPosition(ArkyMapsDomainModel.Position position);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMapServiceChannel : ArkyMapsClient.ArkyMapServiceReference.IMapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MapServiceClient : System.ServiceModel.DuplexClientBase<ArkyMapsClient.ArkyMapServiceReference.IMapService>, ArkyMapsClient.ArkyMapServiceReference.IMapService {
        
        public MapServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MapServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MapServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MapServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MapServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public ArkyMapsDomainModel.ClientUser Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<ArkyMapsDomainModel.ClientUser> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public void Logout(long userId) {
            base.Channel.Logout(userId);
        }
        
        public System.Threading.Tasks.Task LogoutAsync(long userId) {
            return base.Channel.LogoutAsync(userId);
        }
        
        public ArkyMapsDomainModel.PhoneUser QueryPhoneUserById(long userId) {
            return base.Channel.QueryPhoneUserById(userId);
        }
        
        public System.Threading.Tasks.Task<ArkyMapsDomainModel.PhoneUser> QueryPhoneUserByIdAsync(long userId) {
            return base.Channel.QueryPhoneUserByIdAsync(userId);
        }
        
        public ArkyMapsDomainModel.PhoneUser[] QueryPhoneUsers() {
            return base.Channel.QueryPhoneUsers();
        }
        
        public System.Threading.Tasks.Task<ArkyMapsDomainModel.PhoneUser[]> QueryPhoneUsersAsync() {
            return base.Channel.QueryPhoneUsersAsync();
        }
        
        public bool CreatePhoneUser(ArkyMapsDomainModel.PhoneUser phoneUser) {
            return base.Channel.CreatePhoneUser(phoneUser);
        }
        
        public System.Threading.Tasks.Task<bool> CreatePhoneUserAsync(ArkyMapsDomainModel.PhoneUser phoneUser) {
            return base.Channel.CreatePhoneUserAsync(phoneUser);
        }
        
        public bool ModifyPhoneUser(ArkyMapsDomainModel.PhoneUser phoneUser) {
            return base.Channel.ModifyPhoneUser(phoneUser);
        }
        
        public System.Threading.Tasks.Task<bool> ModifyPhoneUserAsync(ArkyMapsDomainModel.PhoneUser phoneUser) {
            return base.Channel.ModifyPhoneUserAsync(phoneUser);
        }
        
        public bool DeletePhoneUser(ArkyMapsDomainModel.PhoneUser phoneUser) {
            return base.Channel.DeletePhoneUser(phoneUser);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePhoneUserAsync(ArkyMapsDomainModel.PhoneUser phoneUser) {
            return base.Channel.DeletePhoneUserAsync(phoneUser);
        }
    }
}
