//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkyMapService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArkyMapService.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create phone user {0}..
        /// </summary>
        internal static string ERROR_CREATE_PHONE_USER {
            get {
                return ResourceManager.GetString("ERROR_CREATE_PHONE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create position user {0}..
        /// </summary>
        internal static string ERROR_CREATE_POSITION {
            get {
                return ResourceManager.GetString("ERROR_CREATE_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete phone user {0}..
        /// </summary>
        internal static string ERROR_DELETE_PHONE_USER {
            get {
                return ResourceManager.GetString("ERROR_DELETE_PHONE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to modify phone user {0}..
        /// </summary>
        internal static string ERROR_MODIFY_PHONE_USER {
            get {
                return ResourceManager.GetString("ERROR_MODIFY_PHONE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to query client user by its name and password {0}..
        /// </summary>
        internal static string ERROR_QUERY_CLIENT_USER_BY_NAME_AND_PASSWORD {
            get {
                return ResourceManager.GetString("ERROR_QUERY_CLIENT_USER_BY_NAME_AND_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to query phone user by its ID {0}..
        /// </summary>
        internal static string ERROR_QUERY_PHONE_USER_BY_ID {
            get {
                return ResourceManager.GetString("ERROR_QUERY_PHONE_USER_BY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to query phone user by its name and password {0}..
        /// </summary>
        internal static string ERROR_QUERY_PHONE_USER_BY_NAME_AND_PASSWORD {
            get {
                return ResourceManager.GetString("ERROR_QUERY_PHONE_USER_BY_NAME_AND_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to query phone users {0}..
        /// </summary>
        internal static string ERROR_QUERY_PHONE_USERS {
            get {
                return ResourceManager.GetString("ERROR_QUERY_PHONE_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start service {0}..
        /// </summary>
        internal static string ERROR_SERVICE_START {
            get {
                return ResourceManager.GetString("ERROR_SERVICE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed for client user {0}..
        /// </summary>
        internal static string MESSAGE_CLIENT_USER_LOGIN_FAIlED {
            get {
                return ResourceManager.GetString("MESSAGE_CLIENT_USER_LOGIN_FAIlED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client user {0} logged in at {1}..
        /// </summary>
        internal static string MESSAGE_CLIENT_USER_LOGIN_SUCCEEDED {
            get {
                return ResourceManager.GetString("MESSAGE_CLIENT_USER_LOGIN_SUCCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client user ID {0} logged out at {1}..
        /// </summary>
        internal static string MESSAGE_CLIENT_USER_LOGOUT_SUCCEEDED {
            get {
                return ResourceManager.GetString("MESSAGE_CLIENT_USER_LOGOUT_SUCCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed for phone user {0}..
        /// </summary>
        internal static string MESSAGE_PHONE_USER_LOGIN_FAIlED {
            get {
                return ResourceManager.GetString("MESSAGE_PHONE_USER_LOGIN_FAIlED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone user {0} logged in at {1}..
        /// </summary>
        internal static string MESSAGE_PHONE_USER_LOGIN_SUCCEEDED {
            get {
                return ResourceManager.GetString("MESSAGE_PHONE_USER_LOGIN_SUCCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the any key to terminate service..
        /// </summary>
        internal static string MESSAGE_PRESS_ANY_KEY {
            get {
                return ResourceManager.GetString("MESSAGE_PRESS_ANY_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service started..
        /// </summary>
        internal static string MESSAGE_SERVICE_STARTED {
            get {
                return ResourceManager.GetString("MESSAGE_SERVICE_STARTED", resourceCulture);
            }
        }
    }
}
