CREATE TABLE [dbo].[PhoneUser]
(
    [ID] BIGINT IDENTITY NOT NULL CONSTRAINT PK_PhoneUser PRIMARY KEY,
    [UserName] VARCHAR(50) NOT NULL,
    [Password] VARCHAR(50) NOT NULL,
    [Name] VARCHAR(100) NOT NULL,
    [Male] BIT NOT NULL,
    [Email] VARCHAR(50) NOT NULL,
    [Deleted] BIT NOT NULL
)
