//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkyMapsPhoneSimulator.ArkyPhoneServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ArkyMaps.com/PhoneService", ConfigurationName="ArkyPhoneServiceReference.IPhoneService")]
    public interface IPhoneService {
        
        [System.ServiceModel.OperationContractAttribute(Action="ArkyMaps.com/PhoneService/IPhoneService/Login", ReplyAction="ArkyMaps.com/PhoneService/IPhoneService/LoginResponse")]
        long Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="ArkyMaps.com/PhoneService/IPhoneService/Login", ReplyAction="ArkyMaps.com/PhoneService/IPhoneService/LoginResponse")]
        System.Threading.Tasks.Task<long> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="ArkyMaps.com/PhoneService/IPhoneService/NewPosition", ReplyAction="ArkyMaps.com/PhoneService/IPhoneService/NewPositionResponse")]
        void NewPosition(long userId, double longitude, double latitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="ArkyMaps.com/PhoneService/IPhoneService/NewPosition", ReplyAction="ArkyMaps.com/PhoneService/IPhoneService/NewPositionResponse")]
        System.Threading.Tasks.Task NewPositionAsync(long userId, double longitude, double latitude);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhoneServiceChannel : ArkyMapsPhoneSimulator.ArkyPhoneServiceReference.IPhoneService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhoneServiceClient : System.ServiceModel.ClientBase<ArkyMapsPhoneSimulator.ArkyPhoneServiceReference.IPhoneService>, ArkyMapsPhoneSimulator.ArkyPhoneServiceReference.IPhoneService {
        
        public PhoneServiceClient() {
        }
        
        public PhoneServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhoneServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<long> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public void NewPosition(long userId, double longitude, double latitude) {
            base.Channel.NewPosition(userId, longitude, latitude);
        }
        
        public System.Threading.Tasks.Task NewPositionAsync(long userId, double longitude, double latitude) {
            return base.Channel.NewPositionAsync(userId, longitude, latitude);
        }
    }
}
