//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkyMapsDal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArkyMapsDatabaseEntities : DbContext
    {
        public ArkyMapsDatabaseEntities()
            : base("name=ArkyMapsDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ClientUser> ClientUser { get; set; }
        public DbSet<PhoneUser> PhoneUser { get; set; }
        public DbSet<Position> Position { get; set; }
    }
}
