//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkyMapsDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneUser
    {
        public PhoneUser()
        {
            this.Position = new HashSet<Position>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public bool Male { get; set; }
        public string Email { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ICollection<Position> Position { get; set; }
    }
}
