//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkyMapsDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public long ID { get; set; }
        public long PhoneUserId { get; set; }
        public float Longitude { get; set; }
        public float Latitude { get; set; }
    
        public virtual PhoneUser PhoneUser { get; set; }
    }
}
